### PR TITLE
Executable flag ./gradlew for linux

### PR DESCRIPTION
**Pull request by wawwior**

### CODE REVIEW

**Comment by ThatJadenXgamer** [comment]
I don't know much about gradle, what does this do?

**Comment by wawwior** [comment]
It's not a gradle thing its a linux thing. Basically when i pull the origin branch i have to do `chmod +x ./gradlew` every time to actually use gradle. It's more of a convenience thing for me tbh.

**Comment by wawwior** [comment]
https://wiki.archlinux.org/title/File_permissions_and_attributes

**Comment by wawwior** [comment]
I can just use a managed gradle installation

**Pull request closed without merging**
